Projeto-File/Controllers/HospitaisController.cs
using System;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pomelo.EntityFrameworkCore.MySql.Query.Internal;
using Projeto_File.Data;
using Projeto_File.Models;

namespace Projeto_File.Controllers
{
    public class HospitaisController : Controller
    {
        private readonly AppDbContext _dbContext;

        public HospitaisController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult AdicionarHospital()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdicionarHospital(Hospital hospital, IFormFile Imagem)
        {
            if (ModelState.IsValid) {
             
                if (Imagem != null)
                {
                    byte[] fotoHexa;

                    using (var open = Imagem.OpenReadStream())
                    {
                        using(var memory = new MemoryStream())
                        {
                            open.CopyTo(memory);

                            fotoHexa = memory.ToArray();
                        }
                    }

                    hospital.Foto = fotoHexa;
                }

                _dbContext.Hospitais.Add(hospital);
                    await _dbContext.SaveChangesAsync();

                return RedirectToAction("Index", "Home");

            }

            //Caso o modelo esteja inconsistente.
            return View(hospital);
        }

        public IActionResult BuscarHospital()
        {
            var lista = _dbContext.Hospitais.ToList(); 
            
            int objeto = lista.Last().HospitalId;

            byte[] imagem = _dbContext.Hospitais.Find(objeto).Foto;
            
            return File(imagem, "image/jpg");

        }
    }
}

Projeto-File/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projeto_File.Data;
using Projeto_File.Models;
using Projeto_File.Models.ViewModels;
using System.Threading.Tasks;

namespace Projeto_File.Controllers
{

    public class UsuariosController : Controller
    {
        private readonly UserManager<Usuario> _manager;
        private readonly SignInManager<Usuario> _signIn;
        private readonly RoleManager<NivelAcesso> _role;
        private readonly AppDbContext _dbContext;

        public UsuariosController(AppDbContext dbContext, RoleManager<NivelAcesso> role, UserManager<Usuario> manager, SignInManager<Usuario> signIn)
        {
            _manager = manager;
            _signIn = signIn;
            _role = role;
            _dbContext = dbContext;
        }

        public IActionResult ListarUsuarios()
        {

            return Content("Exemplo");
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registrar(RegistroViewModel registro)
        {
            if (ModelState.IsValid)
            {
                var usuario = new Usuario
                {
                    Nome = registro.Nome,
                    Sobrenome = registro.Sobrenome,
                    UserName = registro.NomeUsuario,
                    Email = registro.Email,
                    Cidade = registro.Cidade
                };

                var UsuarioCriado = await _manager.CreateAsync(usuario, registro.Senha);

                if (UsuarioCriado.Succeeded)
                {
                    await _signIn.SignInAsync(usuario, false);

                    return RedirectToAction("Index", "Home");
                }               
            }

            return View(registro);
        }

        public async Task<IActionResult> Sair()
        {
            await _signIn.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }

        //ATRIBUIÇÃO DE PERMISSÕES
        [HttpGet]
        public IActionResult RegistrarPermissao()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegistrarPermissao(NivelAcesso nivelAcesso)
        {
            if (ModelState.IsValid)
            {
                bool permissaoExiste = await _role.RoleExistsAsync(nivelAcesso.Name);

                if (!permissaoExiste)
                {
                    await _role.CreateAsync(nivelAcesso);

                    return RedirectToAction("Index", "Home");
                }
            }

            return View(nivelAcesso);
        }

        [HttpGet]
        public async Task<IActionResult> AssociarPermissao()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewData["UsuarioId"] = new SelectList(await _dbContext.Usuarios.ToListAsync(), "Id", "UserName");
                ViewData["NivelAcessoId"] = new SelectList(await _dbContext.NiveisAcessos.ToListAsync(), "Name", "Name");

                return View();
            }

            return StatusCode(403);
        }

        [HttpPost]
        public async Task<IActionResult> AssociarPermissao(UsuarioRoleViewModel usuarioRole)
        {
            if (ModelState.IsValid)
            {
                var usuario = await _dbContext.Usuarios.FindAsync(usuarioRole.UsuarioId);

                await _manager.AddToRoleAsync(usuario, usuarioRole.NomeRole);

                return RedirectToAction("Index", "Home");
            }

            return View(usuarioRole);

        }
    }
}

Projeto-File/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_File</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto_File</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="RegistrarPermissao"> Níveis de Usuário </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="AssociarPermissao"> Atribuir Permissões </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Hospitais" asp-action="AdicionarHospital"> Hospitais </a>
                        </li>

                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="Registrar"> Registrar-se</a>
        </li>*@



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="p-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Projeto_File - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>